
/* Your custom styles */
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

// Initialize fonts with proper syntax
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // Removed duplicate weights
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${outfit.className} antialiased leading-8 overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}